In [17]:
import torch
from torch.autograd import Variable
from sklearn.datasets import load_iris
from keras.utils import to_categorical

#batch size
batch_size=10

#loading iris data from sklearn
iris = load_iris()

x_data=iris.data
y_data=iris.target

#one hot encoding
y_data = to_categorical(y_data)

#numpy to pytorch variable
x_data = Variable(torch.from_numpy(x_data).double())
y_data = Variable(torch.from_numpy(y_data).double())


Using TensorFlow backend.


In [18]:
y_data

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1

In [41]:

class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.l1 = torch.nn.Linear(4, 6)
        self.l2 = torch.nn.Linear(6, 4)
        self.l3 = torch.nn.Linear(4, 3)
        self.sigmoid=torch.nn.Sigmoid()
        self.relu=torch.nn.ReLU()
        self.dropout = torch.nn.Dropout(p=0.5, inplace=False)
        self.softmax = torch.nn.Softmax()
    def forward(self,x):
        out1 = self.l1(x)
#        drop1 = self.dropout(out1)
        out2 = self.relu(self.l2(out1))
#        drop2 = self.dropout(out2)
        y_pred = self.softmax(self.l3(out2))
        return y_pred
        

net = Model().double()

#model summary
print(net)

#binary cross entropy loss
#loss_fun = torch.nn.BCELoss(size_average=True)
loss_fun = torch.nn.CrossEntropyLoss()

#SGD optimizer
import torch.optim as optim

criterion = torch.nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)

permutation = torch.randperm(x_data.size()[0])


Model(
  (l1): Linear(in_features=4, out_features=6, bias=True)
  (l2): Linear(in_features=6, out_features=4, bias=True)
  (l3): Linear(in_features=4, out_features=3, bias=True)
  (sigmoid): Sigmoid()
  (relu): ReLU()
  (dropout): Dropout(p=0.5, inplace=False)
  (softmax): Softmax(dim=None)
)


In [42]:
#training
for epoch in range(100):
    print("Epoch: "+str(epoch))
    for i in range(0, x_data.size()[0], batch_size):
        indices = permutation[i:i+batch_size]
        inputs, inputs_y = x_data[indices], y_data[indices]
        
        optimizer.zero_grad()
        outputs = net(inputs)
        
        loss = criterion(outputs, inputs_y)
        
        print(epoch, loss.data)        
        loss.backward()
        optimizer.step()

Epoch: 0
0 tensor(0.4567, dtype=torch.float64)
0 tensor(0.3753, dtype=torch.float64)
0 tensor(0.2888, dtype=torch.float64)
0 tensor(0.3567, dtype=torch.float64)
0 tensor(0.3125, dtype=torch.float64)
0 tensor(0.2004, dtype=torch.float64)
0 tensor(0.2637, dtype=torch.float64)
0 tensor(0.2996, dtype=torch.float64)
0 tensor(0.2682, dtype=torch.float64)
0 tensor(0.4089, dtype=torch.float64)
0 tensor(0.2630, dtype=torch.float64)
0 tensor(0.2850, dtype=torch.float64)
0 tensor(0.2330, dtype=torch.float64)
0 tensor(0.2887, dtype=torch.float64)
0 tensor(0.1731, dtype=torch.float64)
Epoch: 1
1 tensor(0.3752, dtype=torch.float64)
1 tensor(0.3227, dtype=torch.float64)
1 tensor(0.2535, dtype=torch.float64)
1 tensor(0.3044, dtype=torch.float64)
1 tensor(0.2720, dtype=torch.float64)
1 tensor(0.1919, dtype=torch.float64)
1 tensor(0.2350, dtype=torch.float64)
1 tensor(0.2610, dtype=torch.float64)
1 tensor(0.2405, dtype=torch.float64)
1 tensor(0.3440, dtype=torch.float64)
1 tensor(0.2396, dtype=torch.flo

/Users/raul.reguillo/.pyenv/versions/3.6.8/lib/python3.6/site-packages/ipykernel_launcher.py:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  app.launch_new_instance()


tensor(0.2216, dtype=torch.float64)
14 tensor(0.2074, dtype=torch.float64)
14 tensor(0.2287, dtype=torch.float64)
14 tensor(0.1966, dtype=torch.float64)
14 tensor(0.2237, dtype=torch.float64)
14 tensor(0.1862, dtype=torch.float64)
14 tensor(0.2300, dtype=torch.float64)
14 tensor(0.1868, dtype=torch.float64)
Epoch: 15
15 tensor(0.2484, dtype=torch.float64)
15 tensor(0.2080, dtype=torch.float64)
15 tensor(0.2153, dtype=torch.float64)
15 tensor(0.2225, dtype=torch.float64)
15 tensor(0.2114, dtype=torch.float64)
15 tensor(0.1934, dtype=torch.float64)
15 tensor(0.2173, dtype=torch.float64)
15 tensor(0.2212, dtype=torch.float64)
15 tensor(0.2068, dtype=torch.float64)
15 tensor(0.2275, dtype=torch.float64)
15 tensor(0.1955, dtype=torch.float64)
15 tensor(0.2234, dtype=torch.float64)
15 tensor(0.1851, dtype=torch.float64)
15 tensor(0.2300, dtype=torch.float64)
15 tensor(0.1863, dtype=torch.float64)
Epoch: 16
16 tensor(0.2481, dtype=torch.float64)
16 tensor(0.2067, dtype=torch.float64)
16 tenso

29 tensor(0.1992, dtype=torch.float64)
29 tensor(0.1813, dtype=torch.float64)
29 tensor(0.2086, dtype=torch.float64)
29 tensor(0.2117, dtype=torch.float64)
29 tensor(0.1948, dtype=torch.float64)
29 tensor(0.2152, dtype=torch.float64)
29 tensor(0.1804, dtype=torch.float64)
29 tensor(0.2150, dtype=torch.float64)
29 tensor(0.1675, dtype=torch.float64)
29 tensor(0.2231, dtype=torch.float64)
29 tensor(0.1727, dtype=torch.float64)
Epoch: 30
30 tensor(0.2423, dtype=torch.float64)
30 tensor(0.1899, dtype=torch.float64)
30 tensor(0.2064, dtype=torch.float64)
30 tensor(0.2111, dtype=torch.float64)
30 tensor(0.1977, dtype=torch.float64)
30 tensor(0.1807, dtype=torch.float64)
30 tensor(0.2077, dtype=torch.float64)
30 tensor(0.2109, dtype=torch.float64)
30 tensor(0.1933, dtype=torch.float64)
30 tensor(0.2128, dtype=torch.float64)
30 tensor(0.1788, dtype=torch.float64)
30 tensor(0.2140, dtype=torch.float64)
30 tensor(0.1655, dtype=torch.float64)
30 tensor(0.2225, dtype=torch.float64)
30 tensor(0.171

54 tensor(0.1733, dtype=torch.float64)
54 tensor(0.1535, dtype=torch.float64)
54 tensor(0.2017, dtype=torch.float64)
54 tensor(0.1454, dtype=torch.float64)
54 tensor(0.1783, dtype=torch.float64)
54 tensor(0.1272, dtype=torch.float64)
54 tensor(0.1841, dtype=torch.float64)
54 tensor(0.1199, dtype=torch.float64)
Epoch: 55
55 tensor(0.2189, dtype=torch.float64)
55 tensor(0.1687, dtype=torch.float64)
55 tensor(0.1663, dtype=torch.float64)
55 tensor(0.1849, dtype=torch.float64)
55 tensor(0.1634, dtype=torch.float64)
55 tensor(0.1290, dtype=torch.float64)
55 tensor(0.1624, dtype=torch.float64)
55 tensor(0.1713, dtype=torch.float64)
55 tensor(0.1517, dtype=torch.float64)
55 tensor(0.2007, dtype=torch.float64)
55 tensor(0.1440, dtype=torch.float64)
55 tensor(0.1764, dtype=torch.float64)
55 tensor(0.1257, dtype=torch.float64)
55 tensor(0.1820, dtype=torch.float64)
55 tensor(0.1179, dtype=torch.float64)
Epoch: 56
56 tensor(0.2172, dtype=torch.float64)
56 tensor(0.1677, dtype=torch.float64)
56 te

82 tensor(0.1616, dtype=torch.float64)
82 tensor(0.1119, dtype=torch.float64)
82 tensor(0.1501, dtype=torch.float64)
82 tensor(0.1295, dtype=torch.float64)
82 tensor(0.0846, dtype=torch.float64)
82 tensor(0.1027, dtype=torch.float64)
82 tensor(0.1189, dtype=torch.float64)
82 tensor(0.1101, dtype=torch.float64)
82 tensor(0.1845, dtype=torch.float64)
82 tensor(0.1233, dtype=torch.float64)
82 tensor(0.1224, dtype=torch.float64)
82 tensor(0.1106, dtype=torch.float64)
82 tensor(0.1124, dtype=torch.float64)
82 tensor(0.0766, dtype=torch.float64)
Epoch: 83
83 tensor(0.1563, dtype=torch.float64)
83 tensor(0.1617, dtype=torch.float64)
83 tensor(0.1104, dtype=torch.float64)
83 tensor(0.1493, dtype=torch.float64)
83 tensor(0.1288, dtype=torch.float64)
83 tensor(0.0837, dtype=torch.float64)
83 tensor(0.1010, dtype=torch.float64)
83 tensor(0.1175, dtype=torch.float64)
83 tensor(0.1091, dtype=torch.float64)
83 tensor(0.1840, dtype=torch.float64)
83 tensor(0.1230, dtype=torch.float64)
83 tensor(0.120

In [43]:
outputs

tensor([[0.7761, 0.1166, 0.1073],
        [0.8685, 0.0687, 0.0628],
        [0.8249, 0.0909, 0.0843],
        [0.8049, 0.1014, 0.0936],
        [0.7751, 0.1166, 0.1084],
        [0.8715, 0.0677, 0.0608],
        [0.1300, 0.3890, 0.4810],
        [0.8368, 0.0853, 0.0779],
        [0.1871, 0.3878, 0.4251],
        [0.0850, 0.3794, 0.5357]], dtype=torch.float64,
       grad_fn=<SoftmaxBackward>)

In [44]:
inputs_y

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

In [45]:
criterion(outputs, inputs_y)

tensor(0.0641, dtype=torch.float64, grad_fn=<MseLossBackward>)